Align virtual key codes with NVDA vkCodes.
Prime-Access-Consulting/nvda-at-automation pull request #47
Opened 2023-11-27 19:57 UTC by gnarf

Fixes #46

Some additional debugging utility I added to help figure out if others might be wrong has been left in but commented out.  I am not much of a python programmer, and didn't understand the cleanest way to test these but I do think we might want to try creating these gestures at or near startup time to verify the codes are correct.

2023-11-27 23:35 UTC, jscholes requested changes
Thanks for submitting this; it looks good other than a couple of comments.

2023-11-27 23:35 UTC, jscholes commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +	Keys.NUMPAD0: 'numLockNumpad0',
I don't think we want to exclusively use the `numLock` variants of these.  If the intent is ever to trigger an NVDA command that uses a key on the number pad, e.g. numpad 8 to read the current line, these are always carried out with numlock disabled.  Both numlock states should probably be usable via the protocol somehow.

2023-11-27 23:35 UTC, jscholes commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +# Some code that will try to make a gesture from every entry in the special Keys class
If more debugging capabilities are required/useful, we can formally add them in.  In the meantime, please remove this section so that the code is free of commented-out code blocks.

2023-11-27 23:40 UTC, gnarf commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +	Keys.NUMPAD0: 'numLockNumpad0',
The underlying vkCodes doesn't appear to have a non numlock num8 in that case I imagine the correct code would be upArrow

2023-11-27 23:48 UTC, gnarf commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +# Some code that will try to make a gesture from every entry in the special Keys class
To be clear, this chunk of code is only useful to a future maintainer of this python file to uncomment it during dev/testing.

It is confirming at startup time, that all the results from the key mapping can actually be made into a gesture in the underlying NVDA libs.  It is how I discovered the others (semicolon/equals/etc) that weren't being properly mapped.

2023-11-27 23:52 UTC, gnarf commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +# Some code that will try to make a gesture from every entry in the special Keys class
I left it in for y'all to decide how you might want to properly verify these keys. I recognize that this is probably not the best way to do this check at startup (as I was basically bumbling around python documentation to figure out how to iterate them), and was hoping you could take it from here / find a better method for "final inclusion"

2023-11-28 17:08 UTC, gnarf commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +# Some code that will try to make a gesture from every entry in the special Keys class
removed in [3ff3ed5](https://github.com/Prime-Access-Consulting/nvda-at-automation/pull/47/commits/3ff3ed5ad1a82f858dd6da1d1a7269024e913944)

2023-11-28 17:08 UTC, gnarf commented on NVDAPlugin/globalPlugins/CommandSocket/keyboard_input.py
> +	Keys.NUMPAD0: 'numLockNumpad0',
restored in [3ff3ed5](https://github.com/Prime-Access-Consulting/nvda-at-automation/pull/47/commits/3ff3ed5ad1a82f858dd6da1d1a7269024e913944)

2023-12-06 19:36 UTC, gnarf commented
Also found that some errors would happen when in Focus mode it wouldn't press home/up arrow/etc.  Switching to [`emulateGesture`](https://github.com/nvaccess/nvda/blob/7333efad02ef6fb32eeb26aea7751890879f6951/source/inputCore.py#L654) did the trick.

2023-12-06 20:01 UTC, jscholes approved these changes
@gnarf Looks great, thank you!

2023-12-06 20:01 UTC, merged